[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ciofs-drifter-sims"
version = "0.1.0"
description = "A short description of your package"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
dependencies = []